# -*- coding: utf-8 -*-
"""Non-Markovian Supply Chains: Modeling Protein Substitution via Heavy-Tailed Memory Kernels

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15R2dSx80I42a-we52MKFiw1gTwHt3B8-

## α
"""

import numpy as np
from scipy.optimize import minimize

class GMMMenuFitter:
    def __init__(self, data, window, alpha_fixed):
        self.data = data
        self.window = window
        self.alpha_fixed = alpha_fixed
        self.N = len(data) - window

        # Replace the exponential kernel with a heavy-tailed power-law kernel
        lags = np.arange(1, self.window + 1)
        self.kernel = (1 + lags) ** (-self.alpha_fixed)

    def moment_conditions(self, theta: np.ndarray) -> np.ndarray:
        """
        theta = [lambda_0, gamma, beta, logit_base_red, beta_beef]
        Returns an N x 5 matrix of moment conditions g_i(theta).
        """
        lam_0, gamma, beta, logit_base, beta_beef = theta

        # Restrict parameters to valid theoretical domains
        lam_0 = np.clip(lam_0, 0.001, 0.999)
        gamma = np.clip(gamma, 0.0, 50.0)
        beta = np.clip(beta, -5.0, 5.0)
        beta_beef = np.clip(beta_beef, -5.0, 5.0)

        g = np.zeros((self.N, 5)) # Changed to 5 columns

        for idx, i in enumerate(range(self.window, len(self.data))):
            row = self.data.iloc[i]

            # 1. Hazard Decomposition
            base_hazard = 1.0 if row['is_wednesday'] else lam_0
            delta_hazard = base_hazard * gamma * row['vol_memory']

            # Total unclipped hazard for accurate proportional weighting
            total_raw_hazard = base_hazard + delta_hazard
            effective_hazard = np.clip(total_raw_hazard, 0, 1)

            # Moment 1: Overall transition rate matching
            hazard_residual = row['menu_changed_observed'] - effective_hazard
            g[idx, 0] = hazard_residual

            # Moment 2: Volatility sensitivity matching (Brent)
            g[idx, 1] = hazard_residual * row['vol_memory']

            # 2. State Substitution Mixture Model (Evaluated only on change events)
            if row['menu_changed_observed']:
                # Attribution weights
                w_base = base_hazard / total_raw_hazard
                w_shock = delta_hazard / total_raw_hazard

                # Shock-induced substitution probability
                adjusted_logit = logit_base - (beta * row['stress_memory']) - (beta_beef * row['beef_stress_memory']) # Updated to include beef_stress_memory
                p_red_shock = 1.0 / (1.0 + np.exp(-adjusted_logit))

                # Mixture probability: Baseline noise does not alter protein type
                p_red_base = 1.0 / 3.0
                mixture_prob_red = (w_base * p_red_base) + (w_shock * p_red_shock)

                state_residual = row['is_red_observed'] - mixture_prob_red

                # Moment 3: Baseline state matching
                g[idx, 2] = state_residual
                # Moment 4: Price stress sensitivity (weighted by shock isolation) (Brent)
                g[idx, 3] = state_residual * row['stress_memory']
                # Moment 5: Price stress sensitivity (weighted by shock isolation) (Beef) # New moment
                g[idx, 4] = state_residual * row['beef_stress_memory']
            else:
                g[idx, 2] = 0.0
                g[idx, 3] = 0.0
                g[idx, 4] = 0.0

        return g

    def gmm_objective(self, theta, W):
        g = self.moment_conditions(theta)
        # The GMM objective is J = mean(g).T @ W @ mean(g)
        g_mean = np.mean(g, axis=0)
        return g_mean.T @ W @ g_mean

    def fit(self):
        # Initial guess: [lam_0, gamma, beta, logit_base_red, beta_beef]
        theta_init = np.array([0.01, 2.0, 1.0, -0.693, 0.5]) # Added initial guess for beta_beef

        # Define bounds for parameters: [lam_0, gamma, beta, logit_base_red, beta_beef]
        bounds = [
            (0.001, 0.999),  # lam_0: (0, 1)
            (0.0, 50.0),     # gamma: (0, inf)
            (-5.0, 5.0),     # beta: (-inf, inf)
            (-5.0, 5.0),     # logit_base_red: (-inf, inf)
            (-5.0, 5.0)      # beta_beef: (-inf, inf)
        ]

        # Step 1: Minimize using an Identity Weighting Matrix
        W_identity = np.eye(5) # Changed to 5x5
        print("Running Step 1 GMM (Identity Matrix)...")
        # Changed method to 'L-BFGS-B' to support bounds
        res_step1 = minimize(self.gmm_objective, theta_init, args=(W_identity,), method='L-BFGS-B', bounds=bounds)
        theta_step1 = res_step1.x

        # Compute Optimal Weighting Matrix from Step 1 residuals
        g_matrix_step1 = self.moment_conditions(theta_step1)
        g_cov = np.cov(g_matrix_step1, rowvar=False)
        W_optimal = np.linalg.inv(g_cov + np.eye(5) * 1e-6) # Changed to 5x5

        # Step 2: Minimize using Optimal Inverse-Covariance Weighting
        print("Running Step 2 GMM (Optimal Covariance Weighting)...")
        # Changed method to 'L-BFGS-B' to support bounds
        res_step2 = minimize(self.gmm_objective, theta_step1, args=(W_optimal,), method='L-BFGS-B', bounds=bounds)
        theta_step2 = res_step2.x

        return {
            'lambda_0': theta_step2[0],
            'gamma': theta_step2[1],
            'beta': theta_step2[2],
            'logit_base_red': theta_step2[3],
            'beta_beef': theta_step2[4], # New parameter
            'objective_value': res_step2.fun # Changed to actual objective value
        }

"""## β"""

import yfinance as yf
import pandas as pd
import numpy as np

# 1. Fetch live Brent Crude baseline
print("Pulling BZ=F futures...")
brent = yf.download("BZ=F", start="2025-08-01", end="2026-10-01", progress=False)
brent = brent.reindex(pd.date_range(start="2025-08-01", end=brent.index[-1], freq='D')).ffill()
print("Pulling LE=F futures...")
beef = yf.download("LE=F", start="2025-08-01", end="2026-10-01", progress=False)
beef = beef.reindex(pd.date_range(start="2025-08-01", end=beef.index[-1], freq='D')).ffill()

# Ensure both dataframes have the same index for consistent merging
common_index = brent.index.intersection(beef.index)
brent = brent.loc[common_index]
beef = beef.loc[common_index]


# 2. Construct the synthetic operational log
np.random.seed(42)
df_scraped = pd.DataFrame({
    'date': brent.index,
    'is_wednesday': brent.index.weekday == 2,
    # Standardize inputs to prevent gradient explosion
    'brent_returns': brent['Close'].pct_change().fillna(0).values.flatten(),
    'brent_normalized': (brent['Close'] / brent['Close'].iloc[0]).values.flatten(),
    'beef_returns': beef['Close'].pct_change().fillna(0).values.flatten(),
    'beef_normalized': (beef['Close'] / beef['Close'].iloc[0]).values.flatten()
})

# Define window and alpha_fixed for memory calculations
window_val = 30
alpha_fixed_val = 0.8
kernel = (1 + np.arange(1, window_val + 1)) ** (-alpha_fixed_val)

# Calculate vol_memory and stress_memory
df_scraped['vol_memory'] = np.nan
df_scraped['stress_memory'] = np.nan
df_scraped['beef_stress_memory'] = np.nan # New: Beef stress memory

for i in range(window_val, len(df_scraped)):
    # Slice historical returns/prices for the current window
    past_returns_slice = df_scraped['brent_returns'].iloc[i - window_val : i].values
    past_prices_slice = (df_scraped['brent_normalized'].iloc[i - window_val : i] - 1.0).values
    past_beef_prices_slice = (df_scraped['beef_normalized'].iloc[i - window_val : i] - 1.0).values # New: Beef prices slice


    # Calculate memory terms by convolving with the kernel
    df_scraped.loc[i, 'vol_memory'] = np.sum(np.abs(past_returns_slice)[::-1] * kernel)
    df_scraped.loc[i, 'stress_memory'] = np.sum(past_prices_slice[::-1] * kernel)
    df_scraped.loc[i, 'beef_stress_memory'] = np.sum(past_beef_prices_slice[::-1] * kernel) # New: Calculate beef stress memory


# 3. Simulate observed menu states (Injecting the competing risks)
# Baseline 2% daily change chance, forced 100% on Wednesdays
true_hazard = 0.02 + 5.0 * df_scraped['vol_memory'].fillna(0)
df_scraped['menu_changed_observed'] = np.random.rand(len(df_scraped)) < np.clip(true_hazard, 0, 1)
df_scraped.loc[df_scraped['is_wednesday'], 'menu_changed_observed'] = True
# When changed, roughly 33% chance of red meat
df_scraped['is_red_observed'] = np.where(df_scraped['menu_changed_observed'],
                                         (np.random.rand(len(df_scraped)) < 0.33).astype(float),
                                         0.0)

# 4. Execute the Two-Step GMM
fitter = GMMMenuFitter(df_scraped, window=window_val, alpha_fixed=alpha_fixed_val)
results = fitter.fit()
print("\n--- GMM Optimization Results ---")
for key, val in results.items():
    print(f"{key}: {val}")

"""## γ"""

import matplotlib.pyplot as plt

# 1. Extract the substitution parameters from the GMM results
beta_est = results['beta']
logit_base_est = results['logit_base_red']
# Create a 'stress_memory' column, filling with zeros for demonstration purposes
stress_memory = df_scraped['stress_memory'][fitter.window:]
dates = df_scraped['date'][fitter.window:]

# 2. Calculate the latent probability of substituting to Red Meat during a shock
adjusted_logit = logit_base_est - (beta_est * stress_memory)
# Sigmoid function to convert logit back to probability
p_red_shock = 1.0 / (1.0 + np.exp(-adjusted_logit))

# 3. Visualize the Substitution Effect
fig, ax1 = plt.subplots(figsize=(12, 6))

color = 'tab:purple'
ax1.set_xlabel('Date')
ax1.set_ylabel('Cumulative Price Stress Memory', color=color)
ax1.plot(dates, stress_memory, color=color, linewidth=2, label='Energy Stress Kernel')
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()
color = 'tab:red'
ax2.set_ylabel('Probability of Red Meat P(Red | Shock)', color=color)
# Plot probability, setting y-axis from 0 to 1 for percentage scale
ax2.plot(dates, p_red_shock, color=color, linestyle='--', linewidth=2, label='P(Red Meat)')
ax2.set_ylim(0, 1.0)
ax2.tick_params(axis='y', labelcolor=color)

# Add baseline reference line (33%)
ax2.axhline(y=0.333, color='gray', linestyle=':', alpha=0.7, label='Baseline P(Red) = 33%')

fig.suptitle('Protein Substitution: Energy Stress vs. Red Meat Probability')
fig.tight_layout()
plt.show()
# --- 1. Calculate the Derivatives ---

# Analytical Derivative: Marginal effect of stress on probability (dp/dS)
# Formula: -beta * p * (1 - p)
marginal_sensitivity = -beta_est * p_red_shock * (1.0 - p_red_shock)

# Empirical Derivative: Daily rate of change in probability (dp/dt)
# Using np.diff and padding the first element with 0 to match array lengths
dp_dt = np.insert(np.diff(p_red_shock), 0, 0.0)

# --- 2. Visualize the Derivatives ---

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

# Top Panel: Marginal Sensitivity (Elasticity)
color1 = 'tab:red'
ax1.plot(dates, marginal_sensitivity, color=color1, linewidth=2)
ax1.set_ylabel('Sensitivity (dp/dS)', color=color1)
ax1.set_title('Analytical Derivative: Marginal Effect of Price Stress on Red Meat Probability')
ax1.grid(True, alpha=0.3)
ax1.axhline(0, color='black', linewidth=1)

# Bottom Panel: Daily Velocity (Momentum)
color2 = 'tab:blue'
ax2.plot(dates, dp_dt, color=color2, linewidth=1.5, alpha=0.8)
ax2.set_ylabel('Daily Change (Δp/Δt)', color=color2)
ax2.set_xlabel('Date')
ax2.set_title('Empirical Derivative: Day-over-Day Velocity of Menu Shifts')
ax2.grid(True, alpha=0.3)
ax2.axhline(0, color='black', linewidth=1)

fig.tight_layout()
plt.show()

"""## δ"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import timedelta

# --- 1. Simulation Parameters & Historical Slice ---
forecast_days = 60
n_paths = 100  # Number of Monte Carlo trajectories
hist_days = 90
window = fitter.window

last_date = df_scraped['date'].max()
hist_start = last_date - timedelta(days=hist_days)
hist_df = df_scraped[df_scraped['date'] >= hist_start].copy()

# Extract historical drift and volatility for Brent (BZ=F)
returns_brent_hist = df_scraped['brent_returns'].replace([np.inf, -np.inf], np.nan).dropna()
mu_brent = returns_brent_hist.mean()
sigma_brent = returns_brent_hist.std()
last_norm_brent_price = df_scraped['brent_normalized'].iloc[-1]
seed_brent_prices = df_scraped['brent_normalized'].iloc[-window:].values
seed_brent_returns = df_scraped['brent_returns'].iloc[-window:].values

# Extract historical drift and volatility for Beef (LE=F)
returns_beef_hist = df_scraped['beef_returns'].replace([np.inf, -np.inf], np.nan).dropna()
mu_beef = returns_beef_hist.mean()
sigma_beef = returns_beef_hist.std()
last_norm_beef_price = df_scraped['beef_normalized'].iloc[-1]
seed_beef_prices = df_scraped['beef_normalized'].iloc[-window:].values
seed_beef_returns = df_scraped['beef_returns'].iloc[-window:].values

# --- 2. Monte Carlo Execution Setup ---
future_dates = [last_date + timedelta(days=i) for i in range(1, forecast_days + 1)]

# Generate independent random normal shocks for Brent and Beef for each path and day
np.random.seed(42)
Z_brent = np.random.normal(0, 1, (forecast_days, n_paths))
Z_beef = np.random.normal(0, 1, (forecast_days, n_paths))

# Initialize simulation arrays
sim_brent_prices = np.zeros((forecast_days, n_paths))
sim_brent_returns = np.zeros((forecast_days, n_paths))
sim_beef_prices = np.zeros((forecast_days, n_paths))
sim_beef_returns = np.zeros((forecast_days, n_paths))
sim_hazard = np.zeros((forecast_days, n_paths))
sim_p_red = np.zeros((forecast_days, n_paths))

# Define the sensitivity of beef price drift to red meat substitution probability
price_sensitivity_to_p_red = 0.002

# (Optional but recommended) Clip adjusted_mu_beef so it cannot run away
# This line had a syntax error; np.clip arguments should be in parentheses.
# The clipping was intended to happen during the simulation loop after `adjusted_mu_beef` is calculated.
# Removed from here and will be applied within the loop.

# --- 3. Propagate the Non-Markovian Memory Kernels and Simulate with Feedback ---
for path in range(n_paths):
    # Initialize full history for memory calculation for this path
    # These lists will be dynamically updated with simulated values
    current_full_brent_prices = list(seed_brent_prices - 1.0) # Subtract 1.0 for stress_memory calculation
    current_full_brent_returns = list(seed_brent_returns)
    current_full_beef_prices = list(seed_beef_prices - 1.0) # Subtract 1.0 for stress_memory calculation
    current_full_beef_returns = list(seed_beef_returns)

    # Initialize first day of simulation for both Brent and Beef
    sim_brent_prices[0, path] = last_norm_brent_price * np.exp((mu_brent - 0.5 * sigma_brent**2) + sigma_brent * Z_brent[0, path])
    sim_brent_returns[0, path] = sim_brent_prices[0, path] / last_norm_brent_price - 1.0

    sim_beef_prices[0, path] = last_norm_beef_price * np.exp((mu_beef - 0.5 * sigma_beef**2) + sigma_beef * Z_beef[0, path])
    sim_beef_returns[0, path] = sim_beef_prices[0, path] / last_norm_beef_price - 1.0

    # Append first simulated day's values to history for subsequent memory calculations
    current_full_brent_prices.append(sim_brent_prices[0, path] - 1.0)
    current_full_brent_returns.append(sim_brent_returns[0, path])
    current_full_beef_prices.append(sim_beef_prices[0, path] - 1.0)
    current_full_beef_returns.append(sim_beef_returns[0, path])


    for t in range(forecast_days):
        # Take the last 'window' days for memory calculation
        past_brent_ret_window = np.array(current_full_brent_returns[-window:])
        past_brent_price_window = np.array(current_full_brent_prices[-window:])
        past_beef_price_window = np.array(current_full_beef_prices[-window:])

        # Calculate memory terms
        v_mem = np.sum(np.abs(past_brent_ret_window[::-1]) * fitter.kernel)
        s_mem_brent = np.sum(past_brent_price_window[::-1] * fitter.kernel)
        s_mem_beef = np.sum(past_beef_price_window[::-1] * fitter.kernel)

        # Apply GMM parameters to calculate hazard and P(Red) for *current* time `t`
        sim_hazard[t, path] = results['lambda_0'] * results['gamma'] * v_mem
        # Adjusted logit includes both Brent and Beef stress memories
        adj_logit = results['logit_base_red'] - (results['beta'] * s_mem_brent) - (results['beta_beef'] * s_mem_beef)
        sim_p_red[t, path] = 1.0 / (1.0 + np.exp(-adj_logit))

        if t < forecast_days - 1: # Only simulate if not the last day
            # 1. Simulate next price step for Brent (standard GBM)
            sim_brent_prices[t+1, path] = sim_brent_prices[t, path] * np.exp((mu_brent - 0.5 * sigma_brent**2) + sigma_brent * Z_brent[t+1, path])
            sim_brent_returns[t+1, path] = sim_brent_prices[t+1, path] / sim_brent_prices[t, path] - 1.0

            # 2. Simulate next price step for Beef with feedback from P(Red) from current `t`
            p_red_deviation = sim_p_red[t, path] - (1/3) # Deviation from baseline P(Red)
            # Apply clipping here, after adjusted_mu_beef is calculated
            adjusted_mu_beef = np.clip(mu_beef + price_sensitivity_to_p_red * p_red_deviation, -0.01, 0.01)

            sim_beef_prices[t+1, path] = sim_beef_prices[t, path] * np.exp((adjusted_mu_beef - 0.5 * sigma_beef**2) + sigma_beef * Z_beef[t+1, path])
            sim_beef_returns[t+1, path] = sim_beef_prices[t+1, path] / sim_beef_prices[t, path] - 1.0

            # Append the newly simulated prices and returns for next iteration's memory calculation
            current_full_brent_prices.append(sim_brent_prices[t+1, path] - 1.0)
            current_full_brent_returns.append(sim_brent_returns[t+1, path])
            current_full_beef_prices.append(sim_beef_prices[t+1, path] - 1.0)
            current_full_beef_returns.append(sim_beef_returns[t+1, path])


# --- 4. Plotting the Dashboard ---
# Calculate 5th, 50th (median), and 95th percentiles for the fan charts
pct_brent_price = np.percentile(sim_brent_prices, [5, 50, 95], axis=1)
pct_beef_price = np.percentile(sim_beef_prices, [5, 50, 95], axis=1) # New: Beef prices
pct_hazard = np.percentile(sim_hazard, [5, 50, 95], axis=1)
pct_pred = np.percentile(sim_p_red, [5, 50, 95], axis=1)

# Recalculate historical values for the plot (now also for Beef)
hist_hazard = results['lambda_0'] * results['gamma'] * hist_df['vol_memory']
hist_p_red = 1.0 / (1.0 + np.exp(-(results['logit_base_red'] - results['beta'] * hist_df['stress_memory'] - results['beta_beef'] * hist_df['beef_stress_memory'])))
hist_beef_prices = hist_df['beef_normalized']

fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 12), sharex=True)

# Helper function to plot historical + forecast fan
def plot_forecast_panel(ax, title, hist_y, pct_matrix, color, ylim=None):
    ax.set_title(title)
    ax.plot(hist_df['date'], hist_y, color='black', linewidth=1.5, label='Actual 3-Mo History')
    ax.plot(future_dates, pct_matrix[1], color=color, linestyle='--', label='Median Forecast')
    ax.fill_between(future_dates, pct_matrix[0], pct_matrix[2], color=color, alpha=0.2, label='90% Confidence Interval')
    ax.axvline(last_date, color='gray', linestyle=':', label='Today')
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper left')
    if ylim: ax.set_ylim(ylim)

plot_forecast_panel(ax1, 'Brent Crude Normalized Price', hist_df['brent_normalized'], pct_brent_price, 'tab:red')
plot_forecast_panel(ax2, 'LE=F Normalized Price (with P(Red) Feedback)', hist_beef_prices, pct_beef_price, 'tab:orange') # New plot for Beef
plot_forecast_panel(ax3, 'Latent Menu Shock Hazard (Δλ)', hist_hazard, pct_hazard, 'tab:blue')
plot_forecast_panel(ax4, 'Forecasted Probability of Red Meat (Substitution Effect)', hist_p_red, pct_pred, 'tab:purple', ylim=(0, 1))

plt.xlabel('Date')
plt.tight_layout()
plt.show()